global:
  namespace: dev

services:
  api-gateway:
    image:
      tag: 1b8eb5f

    type: LoadBalancer
    port: 8080
    
  config-server:
    image:
      tag: 1b8eb5f

  discovery-server:
    image:
      tag: 1b8eb5f

  customers-service:
    image:
      tag: 1b8eb5f
    
  vets-service:
    image:
      tag: 1b8eb5f

  visits-service:
    image:
      tag: 1b8eb5f

  
