global:
  namespace: dev

services:
  api-gateway:
    image:
      tag: d59a865
    ingress:
      host: petclinic-dev.com

  config-server:
    image:
      tag: 6af0565

  discovery-server:
    image:
      tag: 6af0565

  customers-service:
    image:
      tag: 44ef3df
    
  vets-service:
    image:
      tag: 44ef3df

  visits-service:
    image:
      tag: a59cbf8

  
