global:
  namespace: dev

services:
  api-gateway:
    image:
      tag: 064b2799

    type: LoadBalancer
    port: 8080
    
  config-server:
    image:
      tag: 1b8eb5f

  discovery-server:
    image:
      tag: 1b8eb5f

  customers-service:
    image:
      tag: e378019d
    
  vets-service:
    image:
      tag: d0e8a754

  visits-service:
    image:
      tag: 73d19128

  
