global:
  namespace: dev

services:
  api-gateway:
    image:
      tag: 1b8eb5f
      
    service:
      type: LoadBalancer
      port: 8080
    
    ingress:
      enabled: false   # optional - nếu dùng LoadBalancer thay vì Ingress
      host: petclinic.com

  config-server:
    image:
      tag: 1b8eb5f

  discovery-server:
    image:
      tag: 1b8eb5f

  customers-service:
    image:
      tag: 1b8eb5f
    
  vets-service:
    image:
      tag: 1b8eb5f

  visits-service:
    image:
      tag: 1b8eb5f

  
